### ISSUE TITLE
sync_pipx shouldn't sync, just install the package

### ISSUE THREAD

**Issue by rsyring** [level12/reqs#4]
And assume the project has specified all the settings correctly.

Could also add the ability to, in the config, specify optional dependencies when installing the package:

```toml

[tool.reqs]
sync_pipx = true

# Like doing `pipx install somepackage[foo,bar]`
synx_pipx_extras = 'foo,bar'

```
