### ISSUE TITLE
Don't presume pip

### ISSUE THREAD

**Issue by rsyring** [level12/reqs#9]
* We currently presume pip is available to install uv
* When uv is already present on the system, mise will use uv to create a project virtualenv
  * [uv virtualenvs do not install pip](https://mise.jdx.dev/lang/python.html#mise-uv)
* `reqs bootstrap` will then try to install uv with pip and throw an error b/c pip isn't available

Related: why are we installing uv if it's already present?

**Comment by rsyring** [comment]
FYI, you can tell UV to install pip when it creates the virtualenv:

```toml
[env]
_.python.venv.path = '{% if env.VIRTUALENVS_DIR %}{{ env.VIRTUALENVS_DIR }}/reach-v2{% else %}.venv{% endif %}'
_.python.venv.create = true
_.python.venv.uv_create_args = ['--seed']
```
